package org.reminderservice.correlation;

/**
 * Header/MDC key constants shared by the REST filter and the Kafka listener
 * so every request or event handled by this service is tagged with the
 * correlation id it arrived with (generated by task-service, or generated
 * here as a fallback for direct calls).
 */
public final class CorrelationIdContext {

    public static final String HEADER_NAME = "X-Correlation-Id";
    public static final String MDC_KEY = "correlationId";

    private CorrelationIdContext() {}
}
