CREATE TABLE reminders (
    reminder_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id     UUID NOT NULL,
    message     VARCHAR(255) NOT NULL
);

CREATE INDEX idx_reminders_task_id ON reminders (task_id);
